#include "snapshot_exporter_internal.h"

#include "output/command_output.h"

#include <algorithm>
#include <filesystem>
#include <sstream>
#include <string>
#include <vector>

namespace {

std::string lua_escape(const std::string& s) {
	std::string out;
	out.reserve(s.size());
	for (const char c : s) {
		if (c == '\\') {
			out += "\\\\";
		} else if (c == '"') {
			out += "\\\"";
		} else {
			out += c;
		}
	}
	return out;
}

} // namespace

namespace snapshot_exporter_internal {

std::vector<InstalledEntry> load_sorted_snapshot_entries(const ReqPackConfig& config) {
	HistoryManager history(config);
	std::vector<InstalledEntry> sorted = history.loadInstalledState();
	std::sort(sorted.begin(), sorted.end(), [](const InstalledEntry& a, const InstalledEntry& b) {
		if (a.system != b.system) {
			return a.system < b.system;
		}
		return a.name < b.name;
	});
	return sorted;
}

std::string build_snapshot_rendered_text(const std::vector<InstalledEntry>& entries) {
	std::ostringstream out;
	out << "-- Generated by ReqPack snapshot\n";
	out << "return {\n";
	out << "  packages = {\n";
	for (const InstalledEntry& e : entries) {
		out << "    { system = \"" << lua_escape(e.system)
			<< "\", name = \"" << lua_escape(e.name)
			<< "\", version = \"" << lua_escape(e.version)
			<< "\" },\n";
	}
	out << "  },\n";
	out << "}\n";
	return out.str();
}

std::string resolved_output_path(const Request& request) {
	if (!request.outputPath.empty()) {
		return request.outputPath;
	}
	return {};
}

} // namespace snapshot_exporter_internal

std::string SnapshotExporter::resolveOutputPath(const Request& request) const {
	return snapshot_exporter_internal::resolved_output_path(request);
}

std::string SnapshotExporter::render(const std::vector<InstalledEntry>& entries) const {
	return snapshot_exporter_internal::build_snapshot_rendered_text(entries);
}

CommandOutput SnapshotExporter::buildSnapshotOutput(const Request& request) const {
	const std::vector<InstalledEntry> sorted = snapshot_exporter_internal::load_sorted_snapshot_entries(this->config);
	const std::string rendered = render(sorted);
	const std::string outputPath = resolveOutputPath(request);

	CommandOutput output;
	output.mode = DisplayMode::SNAPSHOT;
	output.sessionItems = {"snapshot"};
	output.success = true;
	output.succeeded = 1;

	if (sorted.empty()) {
		output.blocks.push_back(make_command_message_block(
			"snapshot: no installed packages tracked in history. Ensure history.trackInstalled is enabled in your config."));
	}

	std::vector<CommandOutputField> fields;
	fields.push_back(CommandOutputField{.key = "Format", .value = "reqpack.lua"});
	fields.push_back(CommandOutputField{.key = "Package Count", .value = std::to_string(sorted.size())});
	if (outputPath.empty()) {
		fields.push_back(CommandOutputField{.key = "Output", .value = "stdout"});
		output.blocks.push_back(make_command_field_value_block(fields));
		output.blocks.push_back(make_command_raw_text_block(rendered));
		return output;
	}

	std::filesystem::path filePath(outputPath);
	if (filePath.is_relative()) {
		filePath = std::filesystem::current_path() / filePath;
	}
	fields.push_back(CommandOutputField{.key = "Output Path", .value = filePath.string()});
	output.blocks.push_back(make_command_field_value_block(fields));
	output.blocks.push_back(make_command_artifact_block("artifact", filePath.string()));
	return output;
}
